/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.soapboxrace.jlauncher.swing;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import br.com.soapboxrace.jlauncher.LoginCreate;
import br.com.soapboxrace.jlauncher.Main;
import br.com.soapboxrace.jlauncher.util.LocaleList;
import br.com.soapboxrace.jlauncher.util.LocaleLoader;
import br.com.soapboxrace.jlauncher.util.ServerList;
import br.com.soapboxrace.jlauncher.vo.ConfigVO;
import br.com.soapboxrace.jlauncher.vo.LocaleVO;
import br.com.soapboxrace.jlauncher.vo.LoginOkVO;

/**
 *
 * @author nils
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5483993078168848130L;

	private LoginOkVO loginOkVO;
	private ConfigVO configVO = Main.loadConfig();
	private ServerList serverList = new ServerList();

	/**
	 * Creates new form MainWindow
	 */
	public MainWindow() {
		initComponents();
		loadLocale();
		serverAddrCombo.removeAllItems();
		serverAddrCombo.addItem(configVO.getServerURL());
		loginEmailText.setText(configVO.getEmail());
		if (!configVO.getGameExePath().isEmpty()) {
			pathLabel.setText(configVO.getGameExePath());
			checkGameFile(configVO.getGameExePath());
		}
		String passwordSHA1 = configVO.getPasswordSHA1();
		if (!passwordSHA1.isEmpty()) {
			loginPasswordText.setText("********************");
		}
		launcherLanguageCombo.removeAllItems();
		LocaleList localeList = new LocaleList();
		ArrayList<LocaleVO> localeList2 = localeList.getLocaleList();
		for (LocaleVO localeVO : localeList2) {
			launcherLanguageCombo.addItem(localeVO);
			if (configVO.getLocale().equals(localeVO.getLocale())) {
				launcherLanguageCombo.setSelectedItem(localeVO);
			}
		}
		launcherLanguageCombo.addItemListener(new ItemListener() {
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == 1) {
					LocaleVO item = (LocaleVO) e.getItem();
					configVO.setLocale(item.getLocale());
					Main.configDao.saveConfig(configVO);
					JOptionPane.showMessageDialog(null, "Language changed, closing!");
					System.exit(0);
				}
			}
		});
		loginSaveCredentialsCheckBox.setSelected(configVO.isSaveCredentials());
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		fileChooser = new javax.swing.JFileChooser();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		mainTabbedPane = new javax.swing.JTabbedPane();
		launcherPanel = new javax.swing.JPanel();
		launcherEmailLbl = new javax.swing.JLabel();
		launcherPasswordLbl = new javax.swing.JLabel();
		loginEmailText = new javax.swing.JTextField();
		loginPasswordText = new javax.swing.JPasswordField();
		loginButton = new javax.swing.JButton();
		loginSaveCredentialsCheckBox = new javax.swing.JCheckBox();
		launcherLanguageCombo = new javax.swing.JComboBox<>();
		loginLanguageLbl = new javax.swing.JLabel();
		createPanel = new javax.swing.JPanel();
		createInviteTicketLbl = new javax.swing.JLabel();
		createPasswordLbl = new javax.swing.JLabel();
		createConfirmPasswordLbl = new javax.swing.JLabel();
		createTicketText = new javax.swing.JTextField();
		createPasswd1Text = new javax.swing.JPasswordField();
		createPasswd2Text = new javax.swing.JPasswordField();
		createEmailLbl = new javax.swing.JLabel();
		createEmailText = new javax.swing.JTextField();
		createButton = new javax.swing.JButton();
		serverAddrLbl = new javax.swing.JLabel();
		pathLabel = new javax.swing.JLabel();
		changeGamePathButton = new javax.swing.JButton();
		launchButton = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		messageLabel = new javax.swing.JLabel();
		serverAddrCombo = new javax.swing.JComboBox<>();
		srvListButton = new javax.swing.JButton();

		jLabel1.setText("jLabel1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		mainTabbedPane.setEnabled(false);

		launcherEmailLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		launcherEmailLbl.setText("launcher.email");

		launcherPasswordLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		launcherPasswordLbl.setText("launcher.password");

		loginEmailText.setEnabled(false);

		loginPasswordText.setEnabled(false);

		loginButton.setText("launcher.login");
		loginButton.setEnabled(false);
		loginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginButtonActionPerformed(evt);
			}
		});

		loginSaveCredentialsCheckBox.setText("launcher.save.credentials");
		loginSaveCredentialsCheckBox.setEnabled(false);

		launcherLanguageCombo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				launcherLanguageComboActionPerformed(evt);
			}
		});

		loginLanguageLbl.setText("launcher.language");

		javax.swing.GroupLayout launcherPanelLayout = new javax.swing.GroupLayout(launcherPanel);
		launcherPanel.setLayout(launcherPanelLayout);
		launcherPanelLayout.setHorizontalGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(launcherPanelLayout
				.createSequentialGroup().addContainerGap()
				.addGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(launcherPasswordLbl).addComponent(launcherEmailLbl)
						.addComponent(loginLanguageLbl))
				.addGap(18, 18, 18)
				.addGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, launcherPanelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(loginButton))
						.addComponent(loginEmailText, javax.swing.GroupLayout.Alignment.TRAILING).addComponent(loginPasswordText, javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(launcherPanelLayout.createSequentialGroup()
								.addGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(launcherLanguageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(loginSaveCredentialsCheckBox))
								.addGap(0, 395, Short.MAX_VALUE)))
				.addContainerGap()));
		launcherPanelLayout.setVerticalGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(launcherPanelLayout.createSequentialGroup()
				.addContainerGap()
				.addGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(launcherEmailLbl).addComponent(loginEmailText,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(launcherPasswordLbl).addComponent(loginPasswordText,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(loginSaveCredentialsCheckBox).addGap(18, 18, 18)
				.addGroup(
						launcherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(launcherLanguageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(loginLanguageLbl))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE).addComponent(loginButton).addContainerGap()));

		mainTabbedPane.addTab("launcher.tab", launcherPanel);

		createInviteTicketLbl.setText("create.invite.ticket");

		createPasswordLbl.setText("create.password");

		createConfirmPasswordLbl.setText("create.confirm.password");

		createEmailLbl.setText("create.email");

		createButton.setText("create.create.account.btn");
		createButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
		createPanel.setLayout(createPanelLayout);
		createPanelLayout.setHorizontalGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(createPanelLayout.createSequentialGroup()
						.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(createPanelLayout.createSequentialGroup().addContainerGap()
										.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(createPasswordLbl)
												.addComponent(createConfirmPasswordLbl).addComponent(createEmailLbl).addComponent(createInviteTicketLbl))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(createEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
												.addComponent(createTicketText, javax.swing.GroupLayout.Alignment.LEADING).addComponent(createPasswd2Text)
												.addComponent(createPasswd1Text, javax.swing.GroupLayout.Alignment.LEADING)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										createPanelLayout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(createButton)))
						.addContainerGap()));
		createPanelLayout.setVerticalGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(createPanelLayout.createSequentialGroup()
				.addContainerGap()
				.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(createInviteTicketLbl).addComponent(createTicketText,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(createEmailLbl).addComponent(createEmailText,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(createPasswordLbl).addComponent(createPasswd1Text,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(
						createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(createPasswd2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(createConfirmPasswordLbl))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(createButton)
				.addContainerGap()));

		mainTabbedPane.addTab("create.account.tab", createPanel);

		serverAddrLbl.setText("main.server.address");

		pathLabel.setText("...");

		changeGamePathButton.setText("main.change.game.path.btn");
		changeGamePathButton.setToolTipText("");
		changeGamePathButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				changeGamePathButtonActionPerformed(evt);
			}
		});

		launchButton.setText("main.launch.game");
		launchButton.setEnabled(false);
		launchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				launchButtonActionPerformed(evt);
			}
		});

		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		messageLabel.setText("<html><b>SoapBox Race World Online Launcher beta v0.0.7</b></html>");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(messageLabel).addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel4Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		messageLabel.getAccessibleContext().setAccessibleName("messageLabel");

		serverAddrCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "main.get.server.list.combo" }));
		serverAddrCombo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				serverAddrComboActionPerformed(evt);
			}
		});

		srvListButton.setText("main.get.server.list.btn");
		srvListButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				srvListButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(mainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(launchButton))
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(changeGamePathButton).addGap(18, 18, 18).addComponent(pathLabel))
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(serverAddrLbl).addGap(18, 18, 18).addComponent(serverAddrCombo, 0,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addGap(18, 18, 18).addComponent(srvListButton)))
						.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(serverAddrLbl).addComponent(serverAddrCombo,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(srvListButton)).addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(changeGamePathButton).addComponent(pathLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(mainTabbedPane).addGap(18, 18, 18)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(launchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void launcherLanguageComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_launcherLanguageComboActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_launcherLanguageComboActionPerformed

	private void serverAddrComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serverAddrComboActionPerformed
		// TODO add your handling code here:
		serverAddrCombo.getItemAt(0);
	}// GEN-LAST:event_serverAddrComboActionPerformed

	private void srvListButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_srvListButtonActionPerformed
		serverAddrCombo.removeAllItems();
		try {
			String[] serverListStr = serverList.getServerList();
			for (String string : serverListStr) {
				serverAddrCombo.addItem(string);
			}
		} catch (Exception e) {
			setErrorMessage("Error loading server list");
		}
	}// GEN-LAST:event_srvListButtonActionPerformed

	private void changeGamePathButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changeGamePathButtonActionPerformed
		int returnVal = fileChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = fileChooser.getSelectedFile();
			String path = file.getAbsolutePath();
			pathLabel.setText(path);
			Main.saveGamePath(path);
			checkGameFile(path);
		}
	}// GEN-LAST:event_changeGamePathButtonActionPerformed

	private void launchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_launchButtonActionPerformed
		String token = loginOkVO.getLoginToken();
		String userId = loginOkVO.getUserId();
		String srvStr = getUrl() + "/soapbox-race-core/Engine.svc";
		String gamePath = pathLabel.getText();
		ProcessBuilder processBuilder = new ProcessBuilder(gamePath, "US", srvStr, token, userId);
		try {
			processBuilder.start();
			System.exit(0);
		} catch (IOException e) {
			setErrorMessage(e.getMessage());
			e.printStackTrace();
		}
	}// GEN-LAST:event_launchButtonActionPerformed

	private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createButtonActionPerformed
		String email = createEmailText.getText();
		if (!Main.copyModules(pathLabel.getText())) {
			setErrorMessage("Can't copy module files to game folder, please check folder permissions.");
			launchButton.setEnabled(false);
			return;
		}
		if (!Main.checkEmail(email)) {
			setErrorMessage("Invalid e-mail!");
			launchButton.setEnabled(false);
			return;
		}
		try {
			String url = getUrl();

			String password1 = new String(createPasswd1Text.getPassword());
			String password2 = new String(createPasswd2Text.getPassword());
			String ticket = createTicketText.getText();
			LoginCreate create = Main.create(url, email, password1);
			boolean doCreate = create.doCreate(password2, ticket);
			if (!doCreate) {
				launchButton.setEnabled(false);
				setErrorMessage(create.getMessage());
			} else {
				launchButton.setEnabled(true);
				setMessage(create.getMessage() + " Launch Game!");
			}
			loginOkVO = create.getLoginOkVO();
		} catch (Exception e) {
			setErrorMessage(e.getMessage());
		}
	}// GEN-LAST:event_createButtonActionPerformed

	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed
		if (!Main.copyModules(pathLabel.getText())) {
			setErrorMessage("Can't copy module files to game folder, please check folder permissions, or run as admin");
			launchButton.setEnabled(false);
			return;
		}
		String url = getUrl();
		String email = loginEmailText.getText();
		String password = new String(loginPasswordText.getPassword());
		LoginCreate login = Main.login(url, email, password, loginSaveCredentialsCheckBox.isSelected());
		if (login.doLogin()) {
			loginOkVO = login.getLoginOkVO();
			launchButton.setEnabled(true);
			setMessage("Login OK, Launch Game!");
		} else {
			loginOkVO = null;
			String message = login.getMessage();
			launchButton.setEnabled(false);
			setErrorMessage(message);
		}
	}// GEN-LAST:event_loginButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton changeGamePathButton;
	private javax.swing.JButton createButton;
	private javax.swing.JLabel createConfirmPasswordLbl;
	private javax.swing.JLabel createEmailLbl;
	private javax.swing.JTextField createEmailText;
	private javax.swing.JLabel createInviteTicketLbl;
	private javax.swing.JPanel createPanel;
	private javax.swing.JPasswordField createPasswd1Text;
	private javax.swing.JPasswordField createPasswd2Text;
	private javax.swing.JLabel createPasswordLbl;
	private javax.swing.JTextField createTicketText;
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JButton launchButton;
	private javax.swing.JLabel launcherEmailLbl;
	private javax.swing.JComboBox<br.com.soapboxrace.jlauncher.vo.LocaleVO> launcherLanguageCombo;
	private javax.swing.JPanel launcherPanel;
	private javax.swing.JLabel launcherPasswordLbl;
	private javax.swing.JButton loginButton;
	private javax.swing.JTextField loginEmailText;
	private javax.swing.JLabel loginLanguageLbl;
	private javax.swing.JPasswordField loginPasswordText;
	private javax.swing.JCheckBox loginSaveCredentialsCheckBox;
	private javax.swing.JTabbedPane mainTabbedPane;
	private javax.swing.JLabel messageLabel;
	private javax.swing.JLabel pathLabel;
	private javax.swing.JComboBox<String> serverAddrCombo;
	private javax.swing.JLabel serverAddrLbl;
	private javax.swing.JButton srvListButton;
	// End of variables declaration//GEN-END:variables

	public void setErrorMessage(String message) {
		messageLabel.setText("<html><font color='red'><b>" + message + "</b></font></html>");
	}

	public void setMessage(String message) {
		messageLabel.setText("<html><b>" + message + "</b></html>");
	}

	public void enableAll() {
		mainTabbedPane.setEnabled(true);
		loginEmailText.setEnabled(true);
		loginPasswordText.setEnabled(true);
		loginSaveCredentialsCheckBox.setEnabled(true);
		loginButton.setEnabled(true);
	}

	public void disableAll() {
		mainTabbedPane.setSelectedIndex(0);
		mainTabbedPane.setEnabled(false);
		loginEmailText.setEnabled(false);
		loginPasswordText.setEnabled(false);
		loginSaveCredentialsCheckBox.setEnabled(false);
		loginButton.setEnabled(false);
	}

	private void checkGameFile(String path) {
		if (Main.checkGameMd5(path)) {
			enableAll();
			setMessage("SoapBox Race World Online Launcher beta v0.0.7");
		} else {
			disableAll();
			setErrorMessage("Invalid or modded game file!");
		}
	}

	private String getUrl() {
		String selectedItem = (String) serverAddrCombo.getSelectedItem();
		String[] split = selectedItem.split(";");
		System.out.println(split[1]);
		return split[1];
	}

	private void loadLocale() {
		ArrayList<Object> windowObjects = new ArrayList<>();
		windowObjects.add(serverAddrLbl);
		// windowObjects.add(serverAddrCombo);
		windowObjects.add(srvListButton);
		windowObjects.add(changeGamePathButton);
		windowObjects.add(mainTabbedPane);
		windowObjects.add(launcherEmailLbl);
		windowObjects.add(launcherPasswordLbl);
		windowObjects.add(loginSaveCredentialsCheckBox);
		windowObjects.add(loginButton);
		// windowObjects.add(mainTabbedPane.getComponent(1));
		windowObjects.add(createInviteTicketLbl);
		windowObjects.add(createEmailLbl);
		windowObjects.add(createPasswordLbl);
		windowObjects.add(createConfirmPasswordLbl);
		windowObjects.add(createButton);
		windowObjects.add(launchButton);
		LocaleLoader.loadLocale(windowObjects);
	}
}
